<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=0.3">
    <!-- 最新 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- 可选的Bootstrap主题文件（一般不用引入） -->
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/base.css">
    <link rel="stylesheet" href="/css/docs.css">
    <link rel="stylesheet" href="/css/jquery.datetimepicker.css">

    <link rel="shortcut icon" href="favicon.ico" />
    <script src="/js/jquery.min.js"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.datetimepicker.hour.js"></script>
    <title>测试排课</title>
</head>
<body>
<div class="container content">
    <div class="row" style="margin-top:40px;">
        <div class="col-md-12">
            <style>
                .form-div{display:inline-block; min-width:400px;margin-bottom:15px;}
                .form-div label{width:120px;}
            </style>
            <form class="form-inline" role="form" action = "" method = "POST">
                <div class="form-div" >
                    <label>按每：</label>
                    <select name="type">
                        <option value="0" <?php if(!isset($params['level']) || $params['level'] == '0' ){ echo "selected"; } ?>><?php echo '请选择';?></option>
                        <?php foreach($level as $k=>$v){ ?>
                            <option value="<?php echo $k;?>" <?php if(isset($params['level']) && $params['level'] == $k ){ echo "selected"; } ?>><?php echo $v;?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-div" >
                    <label>排：</label>
                    <input type="text"  name="times" value="<?php if(!empty($params['times'])){ echo $params['times']; } ?>"/>次
                </div>
                <br/>
                <div class="form-div">
                    <label>单次课时：</label>
                    <select name="once">
                        <option value="0" <?php if(!isset($params['once']) || $params['once'] == '0' ){ echo "selected"; } ?>><?php echo '请选择';?></option>
                        <?php foreach($once as $k=>$v){ ?>
                            <option value="<?php echo $k;?>" <?php if(isset($params['once']) && $params['once'] == $k ){ echo "selected"; } ?>><?php echo $v;?></option>
                        <?php } ?>
                    </select>
                </div>
                <br>

                <div class="form-div">
                    <label for="start_time">开始时间:</label>
                    <label >
                        <input type="text" name="start_time" id="start" value="<?php if(isset($params['start_time'])){ echo $params['start_time'] ; } ?>" />
                    </label>
                    <span class="help-block error"></span>
                </div>
                <div class="form-div">
                    <label for="end_time">结束时间:</label>
                    <label >
                        <input type="text" name="end_time" id = "end" value="<?php if(isset($params['end_time'])){ echo $params['end_time'] ; } ?>" />
                    </label>
                </div>
<div id="week">
                <div class="form-div" >
                    <label>按周排第：</label>
                    <select name="week">
                        <option value="0" <?php if(!isset($params['week']) || $params['week'] == '0' ){ echo "selected"; } ?>><?php echo '请选择';?></option>
                        <option value="1" <?php if(isset($params['week']) && $params['week'] == 1 ){ echo "selected"; } ?>>1</option>
                        <option value="2" <?php if(isset($params['week']) && $params['week'] == 2 ){ echo "selected"; } ?>>2</option>
                        <option value="3" <?php if(isset($params['week']) && $params['week'] == 3 ){ echo "selected"; } ?>>3</option>
                    </select>周
                </div>
                <div class="form-div" >
                    <label>周：</label>
                    <select name="this_week">
                        <option value="0" <?php if(!isset($params['week']) || $params['week'] == '0' ){ echo "selected"; } ?>>周日</option>
                        <option value="1" <?php if(isset($params['week']) && $params['week'] == 1 ){ echo "selected"; } ?>>周一</option>
                        <option value="2" <?php if(isset($params['week']) && $params['week'] == 2 ){ echo "selected"; } ?>>周二</option>
                        <option value="3" <?php if(isset($params['week']) && $params['week'] == 3 ){ echo "selected"; } ?>>周三</option>
                        <option value="4" <?php if(isset($params['week']) && $params['week'] == 4 ){ echo "selected"; } ?>>周四</option>
                        <option value="5" <?php if(isset($params['week']) && $params['week'] == 5 ){ echo "selected"; } ?>>周五</option>
                        <option value="6" <?php if(isset($params['week']) && $params['week'] == 6 ){ echo "selected"; } ?>>周六</option>
                    </select>
                </div>
                <a href="">增加</a>
                <br>
</div>
<div id="month">
                <div class="form-div" >
                    <label>按月排第：</label>
                    <select name="month">
                        <option value="0" <?php if(!isset($params['month']) || $params['month'] == '0' ){ echo "selected"; } ?>><?php echo '请选择';?></option>
                        <?php for($i=1;$i<32;$i++){ ?>
                            <option value="<?PHP echo $i?>" <?php if(isset($params['month']) && $params['month'] == $i ){ echo "selected"; } ?>><?PHP echo $i?></option>
                        <?PHP } ?>

                    </select>号
                </div>
                <a href="">增加</a>
                <br>
</div>
<div id="day">

                <div class="form-div">
                    <label for="day">按天排指定时间:</label>
                    <label >
                        <input type="text" name="day" id="day" value="<?php if(isset($params['day'])){ echo $params['day'] ; } ?>" />
                    </label>
                    <span class="help-block error"></span>
                </div>
                <a href="">增加</a>
</div>
                <br>
                <br>
                <div class="form-div" >
                    <label>每周第一天：</label>
                    <input type="radio"  name="first_week" value="0" <?php if(empty($params['first_week']) || $params['first_week']=='0'){ echo 'checked'; } ?>/> 星期天
                    <input type="radio"  name="first_week" value="1" <?php if(!empty($params['first_week']) && $params['first_week']=='2'){ echo 'checked'; } ?>/> 星期一
                </div>
                <br/>
                <button type="submit" class="btn btn-default">计算排课</button>
                <br/><br/>
            </form>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="app-panel-title" >总课次:<?php echo $course_times;?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    <span class="app-panel-title" >总课小时:<?php echo $course_hour;?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    <div style="clear:both;"></div>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered table-striped">
                        <tr><td>时间</td><td>星期</td><td>排课时间范围</td><td>课时</td></tr>
                        <?php foreach($show_list as $val){ ?>
                            <tr>
                                <td><?php echo $val['id'];?></td>
                                <td><?php echo $val['title'];?></td>
                                <td><?php echo $val['category'];?></td>
                                <td><?php echo $val['author'];?></td>
                            </tr>
                        <?php } ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div><script type="text/javascript">
    $( document ).ready(function() {
        jQuery('#start').datetimepicker();
        jQuery( "#end" ).datetimepicker();
        jQuery( "#day" ).datetimepicker();
    });

</script>
</body>
</html>
